# Generated by Django 6.0 on 2026-06-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=20)),
                ('floor', models.CharField(choices=[('1st_floor', '1st Semester'), ('2nd_floor', '2nd Semester')], default='1st_floor', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
