# Generated by Django 6.0 on 2026-06-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0004_alter_studentdocument_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentdocument',
            unique_together={('first_name', 'last_name', 'folder')},
        ),
    ]
