# Generated by Django 6.0 on 2026-06-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0006_alter_studentdocument_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdocument',
            options={'ordering': ['folder'], 'verbose_name': 'Student Document', 'verbose_name_plural': 'Student Documents'},
        ),
    ]
