# Generated by Django 6.0 on 2026-06-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_template_back_template_template_front_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentidentificationcard',
            name='program',
            field=models.CharField(choices=[('BSIT', 'BSIT'), ('BSED', 'BSED'), ('BEED', 'BEED'), ('BSCRIM', 'BSCRIM'), ('BSHM', 'BSHM'), ('DHST', 'DHST'), ('BST', 'BST'), ('BSBA', 'BSBA')], default='BSIT', max_length=50),
        ),
    ]
