# Generated by Django 6.0 on 2026-06-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_studentidentificationcard_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['-id'], 'verbose_name': 'Template', 'verbose_name_plural': 'ID Templates'},
        ),
    ]
