# Generated by Django 6.0 on 2026-06-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentidentificationcard',
            options={'ordering': ['-id'], 'verbose_name': 'Identification Card', 'verbose_name_plural': 'Identification Cards'},
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='date_ended',
            new_name='valid_until',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='semester',
        ),
    ]
