# Generated by Django 6.0 on 2026-06-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_rename_enrollment_template_alter_template_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='back_template',
            field=models.ImageField(blank=True, help_text='Upload the back design of the ID card.', null=True, upload_to='id_templates/back/'),
        ),
        migrations.AddField(
            model_name='template',
            name='front_template',
            field=models.ImageField(blank=True, help_text='Upload the front design of the ID card.', null=True, upload_to='id_templates/front/'),
        ),
    ]
