# Generated by Django 6.0 on 2026-06-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='floor',
            field=models.CharField(choices=[('1st_floor', '1st Floor'), ('2nd_floor', '2nd Floor')], default='1st_floor', max_length=255),
        ),
    ]
