# Generated by Django 6.0 on 2026-06-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_studentdocument'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentdocument',
            unique_together={('first_name', 'last_name')},
        ),
    ]
