# Generated by Django 6.0 on 2026-05-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0002_collection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collection',
            new_name='ExamCategory',
        ),
        migrations.AlterModelOptions(
            name='examcategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exam Category', 'verbose_name_plural': 'Exam Categories'},
        ),
        migrations.RenameField(
            model_name='examcategory',
            old_name='collection_name',
            new_name='category_name',
        ),
    ]
