# Generated by Django 6.0 on 2026-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0004_exam_delete_entranceexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=60, null=True),
        ),
    ]
