# Generated by Django 6.0 on 2026-05-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0005_exam_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': '3. Exam Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrance Exam', 'verbose_name_plural': '1. Entrance Exams'},
        ),
        migrations.AlterModelOptions(
            name='examcategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exam Category', 'verbose_name_plural': '2. Exam Categories'},
        ),
    ]
