# Generated by Django 6.0 on 2026-05-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0006_examquestion_alter_exam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='entrance_exam', max_length=50),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='option_a',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='option_b',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='option_c',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='option_d',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='option_e',
            field=models.CharField(default='None of the above', max_length=255),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
