# Generated by Django 6.0 on 2026-05-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0007_examquestion_correct_option_examquestion_option_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
