# Generated by Django 6.0 on 2026-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0009_examquestion_category_name_examquestion_exam_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examinee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('BSIT', 'Bachelor of Science in Information Technology'), ('BSED', 'B'), ('BEED', 'C'), ('BSCRIM', 'D'), ('BSHM', 'E'), ('DHST', 'E'), ('BST', 'E'), ('BSBA', 'E')], default='BSIT', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Examinee',
                'verbose_name_plural': '2. Examinees',
                'ordering': ['-created_at'],
            },
        ),
    ]
