# Generated by Django 6.0 on 2026-05-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0010_examinee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examinee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Examinee', 'verbose_name_plural': '4. Examinees'},
        ),
        migrations.AddField(
            model_name='examinee',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='examinee',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='examinee',
            name='middle_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='examinee',
            name='program',
            field=models.CharField(choices=[('BSIT', 'Bachelor of Science in Information Technology'), ('BSED', 'Bachelor of Secondary Education'), ('BEED', 'Bachelor of Elementary Education'), ('BSCRIM', 'Bachelor of Science in Criminology'), ('BSHM', 'Bachelor of Science Hospitality Management'), ('DHST', 'DHST (TVET)'), ('BST', 'Bachelor of Science in Tourism'), ('BSBA', 'Bachelor of Science in Business Administration')], default='BSIT', max_length=255),
        ),
    ]
