# Generated by Django 6.0 on 2026-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0013_alter_examinee_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinee',
            name='or_number',
            field=models.CharField(default='', max_length=11),
        ),
    ]
