# Generated by Django 6.0 on 2026-05-30 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0016_examresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresponse',
            options={'ordering': ['-created_at'], 'verbose_name': 'Examinee Answer', 'verbose_name_plural': 'Examinees Answer'},
        ),
        migrations.AlterField(
            model_name='examresponse',
            name='examinee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_response', to='guidance.examinee'),
        ),
        migrations.AlterUniqueTogether(
            name='examresponse',
            unique_together={('examinee_question', 'examinee')},
        ),
    ]
