# Generated by Django 6.0 on 2026-06-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0019_examresponse_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinee',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
