# Generated by Django 6.0 on 2026-05-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0003_rename_collection_examcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrance Exam',
                'verbose_name_plural': 'Entrance Exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='EntranceExam',
        ),
    ]
