# Generated by Django 6.0 on 2026-05-30 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0008_alter_examquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_question', to='guidance.examcategory'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='exam_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_question', to='guidance.exam'),
        ),
    ]
