# Generated by Django 6.0 on 2026-05-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0011_alter_examinee_options_examinee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinee',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='examinee',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='examinee',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
