# Generated by Django 6.0 on 2026-05-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0012_alter_examinee_first_name_alter_examinee_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinee',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
