# Generated by Django 6.0 on 2026-05-30 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0014_examinee_or_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrance Exam', 'verbose_name_plural': 'Entrance Exams'},
        ),
        migrations.AlterModelOptions(
            name='examcategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exam Category', 'verbose_name_plural': 'Exam Categories'},
        ),
        migrations.AlterModelOptions(
            name='examinee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Examinee', 'verbose_name_plural': 'Examinees'},
        ),
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exam Question', 'verbose_name_plural': 'Exam Questions'},
        ),
        migrations.AddField(
            model_name='examinee',
            name='exam_taken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinee', to='guidance.exam'),
        ),
    ]
