# Generated by Django 6.0 on 2026-05-30 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0015_alter_exam_options_alter_examcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinee_response', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examinee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_response', to='guidance.examinee')),
                ('examinee_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_response', to='guidance.examquestion')),
            ],
            options={
                'verbose_name': "Examinees' Answer",
                'verbose_name_plural': "Examinees' Answers",
                'ordering': ['-created_at'],
            },
        ),
    ]
