# Generated by Django 6.0 on 2026-05-30 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0017_alter_examresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresponse',
            name='examinee_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_response', to='guidance.examquestion'),
        ),
    ]
