# Generated by Django 5.2.14 on 2026-06-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0018_alter_examresponse_examinee_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
